---
name: nginx-server

releases:
- name: bpm
  sha1: 0f2efdad0e9702faa23ead010c1b866f985ba537
  url: https://s3.amazonaws.com/bosh-compiled-release-tarballs/bpm-1.1.8-ubuntu-xenial-621.76-20200616-225534-615382607-20200616225536.tgz
  version: 1.1.8
- name: "haproxy"
  version: "10.1.0"
  url: "https://bosh.io/d/github.com/cloudfoundry-community/haproxy-boshrelease?v=10.1.0"
  sha1: "5258d6a8e5aa164b8154a24e0e6db6373755e4fb"
- name: "garden-runc"
  version: "1.15.1"
  url: "https://bosh.io/d/github.com/cloudfoundry/garden-runc-release?v=1.15.1"
  sha1: "bdac2dc7debc2e9b4b9e32f009cb93ac281e5480"

stemcells:
# Centos 3421.11 _appears_ not to work under BOSH Lite
- alias: ubuntu
  os: ubuntu-xenial
  version: latest

instance_groups:
- name: haproxy
  azs: [z1]
  instances: 1
  vm_type: default
  stemcell: ubuntu
  networks: [{name: default}]
  jobs:
  - name: haproxy
    release: haproxy
    properties:
      ha_proxy:
        backend_port: 80
        backend_servers: [10.244.0.2,10.244.0.3]
  - release: garden-runc
    name: garden
    properties:
      garden:
        listen_network: tcp
        listen_address: 0.0.0.0:7777
        allow_host_access: true
  
- name: nginx-server
  instances: 2
  azs: [z1]
  vm_type: default
  persistent_disk_type: default
  stemcell: ubuntu
  networks:
  - name: default
  jobs:
  - name: nginx-server
    release: nginx-server
    properties:
      nginx_conf: |
        user nobody vcap; # group vcap can read most directories
        worker_processes  1;
        error_log /var/vcap/sys/log/nginx/error.log   info;
        events {
          worker_connections  1024;
        }
        http {
          include /var/vcap/packages/nginx/conf/mime.types;
          default_type  application/octet-stream;
          sendfile        on;
          ssi on;
          keepalive_timeout  65;
          server_names_hash_bucket_size 64;
          server {
            server_name _; # invalid value which will never trigger on a real hostname.
            listen *:80;
            # FIXME: replace all occurrences of 'example.com' with your server's FQDN
            access_log /var/vcap/sys/log/nginx/example.com-access.log;
            error_log /var/vcap/sys/log/nginx/example.com-error.log;
            root /var/vcap/data/nginx/document_root;
            index index.shtml;
          }
        }
      pre_start: |
        #!/bin/bash -ex
        NGINX_DIR=/var/vcap/data/nginx/document_root
        if [ ! -d $NGINX_DIR ]; then
          mkdir -p $NGINX_DIR
          cd $NGINX_DIR
          cat > index.shtml <<EOF
            <html><head><title>BOSH on IPv6</title>
            </head><body>
            <h2>Welcome to BOSH's nginx Release</h2>
            <h2>
            My hostname/IP: <b><!--# echo var="HTTP_HOST" --></b><br />
            Your IP: <b><!--# echo var="REMOTE_ADDR" --></b>
            </h2>
            </body></html>
        EOF
        fi
update:
  canaries: 1
  max_in_flight: 1
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
